config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :orders, only: [:index, :show, :create, :new] do 
    collection do
      post :confirm
      get :finsh
    end
  end    
  resources :items, only: [:index, :show] do
    get :autocomplete_item_name, on: :collection 
  end  
  resources :end_users, only: [:edit, :update, :destroy ] 
  resources :cart_items, only: [:show, :update, :create, :destroy, :index]
    delete "destruction", :to => "cart_items#destruction"
 
   devise_for :end_users, :controllers => {
    :registrations => 'end_users/registrations',
    :sessions => 'end_users/sessions'   
  } 

  devise_scope :end_user do
    get "sign_in", :to => "end_users/sessions#new"
    get "sign_out", :to => "end_users/sessions#destroy" 
  end

  get 'end_users/:id', :to => 'end_users#show', as: :end_users_mypage
 namespace :admin do
   resources :order_details, only:[:update]
   resources :items, only: [:index, :new, :create, :update, :edit]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   get "end_users", :to =>"end_users#index"
   delete "end_user/:id", :to =>"end_users#destroy"
   get "", :to =>"end_users#top"

 end
 devise_for :admins, path: :admin, :controllers => {
   
  :sessions => 'admins/sessions'   
} 
devise_scope :admin do
  get "admin/sign_in", :to => "admins/sessions#new"
  get "admin/sign_out", :to => "admins/sessions#destroy" 
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
        @genre = Genre.new
        @genres = Genre.all
    end
    def create
      @genre = Genre.new(genre_params)
      @genre.save
      redirect_to admin_genres_path
    end
    def edit
      @genre = Genre.find(params[:id])

    end
    def update
      @genre = Genre.find(params[:id])
      @genre.update(genre_params)
      redirect_to admin_genres_path

    end   
    
    private
    def genre_params
      params.require(:genre).permit(:name, :effectiveness)
    end	
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
管理者　編集

<%= form_for(@genre, url: admin_genre_path(@genre) ) do |f| %>
	 	<div class="field row">
	 	 <label>ジャンル名</label>
	 	 <%= f.text_field :name, class: "col-xs-12" %>
	 	</div>
	 	<div class="field row">
	 	 <label>有効</label>
	 	<%= f.check_box :effectiveness, {} ,"true", "false"  %>
	 	</div>

	 	<div class="actions row">
	 		<%= f.submit 'update', class: "col-xs-12 btn btn-primary"  %>
	 	</div>
<% end %>       

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
 <h1>管理者　ジャンル　一覧　登録</h1>
  <div class="col-xs-4">
  <%= form_for(@genre, url: admin_genres_path ) do |f| %>
	 	<div class="field row">
	 	 <label>ジャンル名</label>
	 	 <%= f.text_field :name, class: "col-xs-12" %>
	 	</div>
	 	<div class="field row">
	 	 <label>有効</label>
	 	<%= f.check_box :effectiveness, {} ,"true", "false"  %>
	 	</div>

	 	<div class="actions row">
	 		<%= f.submit 'Create', class: "col-xs-12 btn btn-primary"  %>
	 	</div>
<% end %>    
  
 </div>
 <div class="col-xs-8">
 <table class="table">
  <thead>
   <tr>
    <th>ジャンル名     <th>
    <th>有効<th>
	<th>       <th>
   </tr>
  </thead>
  <tbody>
   <% @genres.each do |genre| %>

    <tr>
    <td><%= genre.name %><td>
    <td><%= genre.effectiveness %><td>
	<td><%= link_to "編集", edit_admin_genre_path(genre) %><td>
   </tr>
   <% end %>
  </tbody>
  
 </table>
 </div>
  
 </div>
</div>

   


 