config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :orders, only: [:index, :show, :create, :new] do 
    collection do
      post :confirm
      get :finsh
    end
  end    
  resources :items, only: [:index, :show] do
    get :autocomplete_item_name, on: :collection 
  end  
  resources :end_users, only: [:edit, :update, :destroy ] 
  resources :cart_items, only: [:show, :update, :create, :destroy, :index]
    delete "destruction", :to => "cart_items#destruction"
 
   devise_for :end_users, :controllers => {
    :registrations => 'end_users/registrations',
    :sessions => 'end_users/sessions'   
  } 

  devise_scope :end_user do
    get "sign_in", :to => "end_users/sessions#new"
    get "sign_out", :to => "end_users/sessions#destroy" 
  end

  get 'end_users/:id', :to => 'end_users#show', as: :end_users_mypage
 namespace :admin do
   resources :order_details, only:[:update]
   resources :items, only: [:index, :new, :create, :update, :edit]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   get "end_users", :to =>"end_users#index"
   delete "end_user/:id", :to =>"end_users#destroy"
   get "", :to =>"end_users#top"

 end
 devise_for :admins, path: :admin, :controllers => {
   
  :sessions => 'admins/sessions'   
} 
devise_scope :admin do
  get "admin/sign_in", :to => "admins/sessions#new"
  get "admin/sign_out", :to => "admins/sessions#destroy" 
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user,optional: true
  belongs_to :item, optional: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_end_user!

    def index
      @user = current_end_user
      @carts = current_end_user.cart_items
        
    end
    def show
        @cart = Item.CartItem.new
        @user = current_end_user
        @carts = current_end_user.cart_items
    end    
    def create
      
     if current_end_user.cart_items.find_by(item_id: params[:item_id]).present?
      @cart_items = current_end_user.cart_items
      @cart_items.each do |cart_item|
      if cart_item == current_end_user.cart_items.find_by(item_id: params[:item_id])
         sum = cart_item.amount.to_i + cart_item_params[:amount].to_i
         cart_item.update_attributes(amount: sum)
         redirect_to  cart_items_path
      else   
        
      end
      end  
        
       
     else
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.end_user_id = current_end_user.id
      @cart_item.item_id = params[:item_id]
      @cart_item.save
      redirect_to cart_items_path      
     end
    end 
    
    def same_items
      @cart_items = current_end_user.cart_items
      @cart_items.each do |cart_item|
      if cart_item.item_id == current_end_user.cart_items.find_by(item_id: 2)  
         sum = cart_item.amount.to_i + params[:cart_item][:amount].to_i
         cart_item.update_attributes(amount: sum)
         redirect_to  cart_items_path
      else   
      end
      end  

    end  

    def update
      @cart = CartItem.find(params[:id])
      @cart.update(cart_item_params)
      @cart.end_user_id = current_end_user.id
      redirect_to cart_items_path
    end
    def destroy
      cart = CartItem.find(params[:id])
      cart.destroy
      redirect_to cart_items_path
    end    
    def destruction
      @carts = current_end_user.cart_items
      @carts.each do |cart|
        cart.destroy
      end  
      redirect_to cart_items_path

    end  
      


    private

    
    def cart_item_params
      params.require(:cart_item).permit(:amount, :item_id)
    end

 

         
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb

 <table class="table">
  <thead>
   <tr>
    <th>ユーザー名</th>
    <th>商品名</th>
    <th>値段</th>
    <th>商品数</th>
    <th></th>
    <th></th>
    <th>小計</th>
   <tr>
  </thead>
  <tbody>
   <% @carts.each do |cart| %>

    <tr>
     <td><%= cart.end_user.name %></td>
     <td><%= cart.item.name %></td>
     <td><%= cart.item.price %></td>
         <%= form_for(cart, url: cart_item_path(cart)) do |f| %>
     <td><%= f.number_field :amount, class: "col-xs-12" %></td>
     <td><%= f.submit 'edit amount'%></td>
 <% end %>   
     <td><%= link_to "destroy", cart_item_path(@cart=cart), method: :delete %></td>
     <td><%= cart.item.price*cart.amount %></td>

     <tr>
  </tbody>
         <% end %>

 </table>
        
         <%= link_to "カート内全削除", destruction_path, method: :delete %>
       <%= link_to "購入画面", new_order_path %> 
       <%= link_to "買い物を続ける", items_path %>

app/views/cart_items/show.html.erb
  <% @carts.each do |cart| %>
         <%= cart.end_user.name %>
         <%= cart.amount %>

         <%= form_for(cart, url: cart_item_path(cart)) do |f| %>
	 
         <label>dddd</label>
	 	<%= f.number_field :amount, class: "col-xs-12" %>
	 	</div>
       
         

	 	<div class="actions row">
	 		<%= f.submit 'create book', class: "col-xs-12 btn btn-primary"  %>
	 	</div>
         
<% end %>   
       <% end %>    