config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :orders, only: [:index, :show, :create, :new] do 
    collection do
      post :confirm
      get :finsh
    end
  end    
  resources :items, only: [:index, :show] do
    get :autocomplete_item_name, on: :collection 
  end  
  resources :end_users, only: [:edit, :update, :destroy ] 
  resources :cart_items, only: [:show, :update, :create, :destroy, :index]
    delete "destruction", :to => "cart_items#destruction"
 
   devise_for :end_users, :controllers => {
    :registrations => 'end_users/registrations',
    :sessions => 'end_users/sessions'   
  } 

  devise_scope :end_user do
    get "sign_in", :to => "end_users/sessions#new"
    get "sign_out", :to => "end_users/sessions#destroy" 
  end

  get 'end_users/:id', :to => 'end_users#show', as: :end_users_mypage
 namespace :admin do
   resources :order_details, only:[:update]
   resources :items, only: [:index, :new, :create, :update, :edit]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   get "end_users", :to =>"end_users#index"
   delete "end_user/:id", :to =>"end_users#destroy"
   get "", :to =>"end_users#top"

 end
 devise_for :admins, path: :admin, :controllers => {
   
  :sessions => 'admins/sessions'   
} 
devise_scope :admin do
  get "admin/sign_in", :to => "admins/sessions#new"
  get "admin/sign_out", :to => "admins/sessions#destroy" 
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title>WebcampEcsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class = "navbar navbar-top navbar-inverse">

    <div class = "container">
    <nav class= "navbar-left nabvar-nav nav">
    <% if end_user_signed_in? %>
      <li><a><%= current_end_user.name %></a></li>
      <% end %>
    </nav>
    <% if end_user_signed_in? %>
    <nav>
     <ul class="navbar-right navbar-nav nav" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
     <li>
        <%= link_to " mypage", end_users_mypage_path(current_end_user.id) %>
      </li>
      <li>
        <%= link_to " log out", sign_out_path %>
      </li>
       <li> 
        <%= link_to " 商品一覧", items_path  %>  
      </li>
       <li> 
        <%= link_to " カート内商品一覧", cart_items_path  %>  
      </li>
      <li> 
      <a><%= form_tag(items_path, method: :get, enforce_utf8: false) do %>
       <%= autocomplete_field_tag 'item[name]', nil,  autocomplete_item_name_items_path %>
       <% end %></a>
      </li>
     </ul>
     </nav> 

    <% elsif admin_signed_in? %>  
    <nav>
    <ul class="nav navbar-nav navbar-right">
       <li>
        <%= link_to " 受注一覧", admin_orders_path %>
      </li>
      <li> 
        <%= link_to "商品登録", new_admin_item_path  %>  
      </li>
      <li> 
        <%= link_to "ユーザー一覧", admin_end_users_path  %>  
      </li>
      <li> 
        <%= link_to "ジャンル一覧", admin_genres_path  %>  
      </li>

      <li>
        <%= link_to " log out", admin_sign_out_path %>
      </li>
    <nav>
    <ul>  
   
    <% else %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <%= link_to "  Sign up", new_end_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "  Log in", new_end_user_session_path %>
      </li>
       <li> 
        <%= link_to " 商品一覧", items_path  %>  
      </li>
      <ul>
      <nav>
    <% end %>
    
    </ul>
    </nav>
     <div>
   </header>
    <%= yield %>
  </body>
</html>